import React from 'react';
import { X, FileCheck2, Download, Shield, Layers } from 'lucide-react';
import { CodeFile, Vulnerability } from '../types';

interface AuditReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  activeFile: CodeFile;
  files: CodeFile[];
  vulnerabilities: Vulnerability[];
  securityScore: number;
}

export const AuditReportModal: React.FC<AuditReportModalProps> = ({
  isOpen, onClose, activeFile, files, vulnerabilities, securityScore,
}) => {
  if (!isOpen) return null;

  const criticalCount = vulnerabilities.filter(v => v.severity === 'CRITICAL').length;
  const highCount = vulnerabilities.filter(v => v.severity === 'HIGH').length;
  const mediumCount = vulnerabilities.filter(v => v.severity === 'MEDIUM').length;
  const lowCount = vulnerabilities.filter(v => v.severity === 'LOW').length;

  const getGrade = (score: number) => {
    if (score >= 90) return { grade: 'A+', text: 'Hardened & Production Ready', color: 'var(--success)' };
    if (score >= 80) return { grade: 'A', text: 'Secure with Minor Observations', color: 'var(--success)' };
    if (score >= 70) return { grade: 'B', text: 'Action Recommended', color: '#F59E0B' };
    if (score >= 50) return { grade: 'C', text: 'Elevated Vulnerabilities', color: '#F97316' };
    return { grade: 'F', text: 'Immediate Remediation Required', color: 'var(--critical)' };
  };

  const grade = getGrade(securityScore);

  const downloadMarkdownReport = () => {
    const md = `# Security Audit Report\n**Date:** ${new Date().toISOString()}\n**File:** ${activeFile.name}\n**Score:** ${securityScore}/100 (Grade: ${grade.grade})\n\n## Summary\n${grade.text}. Total findings: **${vulnerabilities.length}** (Critical: ${criticalCount}, High: ${highCount}, Medium: ${mediumCount}, Low: ${lowCount}).\n\n## Findings\n${vulnerabilities.map((v, i) => `\n### ${i + 1}. [${v.severity}] ${v.title}\n- **CWE:** ${v.cwe} | **CVSS:** ${v.cvssScore}\n- **Location:** Lines ${v.lineStart}-${v.lineEnd}\n- **Description:** ${v.description}\n- **Remediation:** ${v.remediation}\n`).join('\n')}\n\n---\n*Generated by Sentinel IDE*`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `Security-Report-${activeFile.name}.md`;
    a.click();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(4px)' }} onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="w-full max-w-2xl max-h-[85vh] flex flex-col overflow-hidden" style={{ backgroundColor: 'var(--bg-surface)', border: '1px solid var(--border)' }}>
        <div className="flex items-center justify-between px-5 py-4 shrink-0" style={{ borderBottom: '1px solid var(--border)' }}>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ backgroundColor: 'var(--success-bg)' }}>
              <FileCheck2 className="w-4 h-4" style={{ color: 'var(--success)' }} />
            </div>
            <div>
              <h2 className="text-sm font-semibold text-white">Security Report</h2>
              <p className="text-[11px]" style={{ color: 'var(--text-muted)' }}>{activeFile.name} • {files.length} files</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={downloadMarkdownReport} className="flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-md cursor-pointer" style={{ color: 'var(--accent)', backgroundColor: 'var(--accent-dim)' }}>
              <Download className="w-3.5 h-3.5" />
              <span>Export</span>
            </button>
            <button onClick={onClose} className="p-1.5 rounded-md cursor-pointer" style={{ color: 'var(--text-muted)' }}>
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {/* Grade Card */}
          <div className="p-5 rounded-lg" style={{ backgroundColor: 'var(--bg-elevated)' }}>
            <div className="flex items-center gap-4 mb-3">
              <div className="w-14 h-14 rounded-lg flex items-center justify-center font-bold text-2xl" style={{ backgroundColor: 'var(--bg-base)', border: `2px solid ${grade.color}`, color: grade.color }}>
                {grade.grade}
              </div>
              <div>
                <div className="text-xs mb-0.5" style={{ color: 'var(--text-muted)' }}>Security Score</div>
                <div className="text-2xl font-bold" style={{ color: grade.color }}>{securityScore}/100</div>
                <div className="text-xs" style={{ color: 'var(--text-secondary)' }}>{grade.text}</div>
              </div>
            </div>
            <div className="grid grid-cols-4 gap-2">
              {[
                { label: 'Critical', count: criticalCount, color: 'var(--critical)' },
                { label: 'High', count: highCount, color: 'var(--high)' },
                { label: 'Medium', count: mediumCount, color: 'var(--medium)' },
                { label: 'Low', count: lowCount, color: 'var(--low)' },
              ].map(item => (
                <div key={item.label} className="text-center p-2 rounded-md" style={{ backgroundColor: 'var(--bg-base)' }}>
                  <div className="text-base font-bold" style={{ color: item.color }}>{item.count}</div>
                  <div className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{item.label}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Findings */}
          <div>
            <h3 className="text-xs font-semibold mb-2" style={{ color: 'var(--text-muted)' }}>
              Findings ({vulnerabilities.length})
            </h3>
            <div className="space-y-2">
              {vulnerabilities.map((v, idx) => {
                const sevColor = v.severity === 'CRITICAL' ? 'var(--critical)' : v.severity === 'HIGH' ? 'var(--high)' : v.severity === 'MEDIUM' ? 'var(--medium)' : 'var(--low)';
                return (
                  <div key={idx} className="p-3 rounded-lg" style={{ backgroundColor: 'var(--bg-elevated)' }}>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded" style={{ color: sevColor, backgroundColor: `${sevColor}15`, border: `1px solid ${sevColor}30` }}>
                        {v.severity}
                      </span>
                      <span className="text-xs font-medium text-white">{v.title}</span>
                      <span className="text-[11px] ml-auto" style={{ color: 'var(--text-muted)' }}>{v.cwe}</span>
                    </div>
                    <p className="text-[11px] leading-relaxed" style={{ color: 'var(--text-muted)' }}>{v.description}</p>
                    <div className="mt-1.5 text-[10px] p-2 rounded" style={{ backgroundColor: 'var(--bg-base)', color: 'var(--success)' }}>
                      Fix: {v.remediation}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        <div className="flex justify-end px-5 py-3 shrink-0" style={{ borderTop: '1px solid var(--border)' }}>
          <button onClick={onClose} className="text-xs font-medium px-3 py-2 rounded-md cursor-pointer" style={{ color: 'var(--text-muted)' }}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
